test: change dockerfile, push same version, commit & add to file

diff --git a/.github/workflows/on_master.yml b/.github/workflows/on_master.yml
--- a/.github/workflows/on_master.yml
+++ b/.github/workflows/on_master.yml
@@ -7,7 +7,7 @@ env:
   BASE_IMAGE_NAME:   "maryamdrv/base-image"
   BASE_IMAGE_TAG:     1.3
   SERVICE_IMAGE_REPO: "maryamdrv/my-simple-image"
-  SERVICE_IMAGE_TAG:  1.8
+  SERVICE_IMAGE_TAG:  1.9
 
 jobs:
   test:
@@ -66,13 +66,13 @@ jobs:
           fi
 
       - name: Build base Docker image
-        # if: env.digest_exists == 'false'
+        if: env.digest_exists == 'false'
         id: build_base_image
         run: |
           ./build_docker_image.sh build_base_image
 
       - name: Push base Docker image
-        # if: env.digest_exists == 'false'
+        if: env.digest_exists == 'false'
         run: |
           docker push $BASE_IMAGE_NAME:$BASE_IMAGE_TAG   
           
@@ -87,89 +87,88 @@ jobs:
           fi
           echo "base_digest=$BASE_DIGEST" >> $GITHUB_OUTPUT
 
-      # - name: Check if service image tag exists
-      #   id: check_service_tag
-      #   run: |
-      #     if docker manifest inspect "$SERVICE_IMAGE_REPO:$SERVICE_IMAGE_TAG" > /dev/null 2>&1; then
-      #       echo "image tag already exists"
-      #       exit 1
-      #     else
-      #       echo "image tag does not exist"
-      #     fi
-      # - name: Build service Docker image
-      #   id: build_service_image
-      #   run: |
-      #     ./build_docker_image.sh build_service_image
+      - name: Check if service image tag exists
+        id: check_service_tag
+        run: |
+          if docker manifest inspect "$SERVICE_IMAGE_REPO:$SERVICE_IMAGE_TAG" > /dev/null 2>&1; then
+            echo "image tag already exists"
+            exit 1
+          else
+            echo "image tag does not exist"
+          fi
+      - name: Build service Docker image
+        id: build_service_image
+        run: |
+          ./build_docker_image.sh build_service_image
 
-      # - name: Push service Docker image
-      #   run: |
-      #     docker push $SERVICE_IMAGE_REPO:$SERVICE_IMAGE_TAG   
+      - name: Push service Docker image
+        run: |
+          docker push $SERVICE_IMAGE_REPO:$SERVICE_IMAGE_TAG   
           
-      # - name: Get service Docker image digest
-      #   id: id_get_service_digest
-      #   run: |
-      #     DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $SERVICE_IMAGE_REPO:$SERVICE_IMAGE_TAG)
-      #     if [ -z "$DIGEST" ]; then
-      #       echo "Failed to retrieve digest for $SERVICE_IMAGE_REPO:$SERVICE_IMAGE_TAG"
-      #       exit 1
-      #     fi
-      #     echo "service_digest=$DIGEST" >> $GITHUB_OUTPUT
+      - name: Get service Docker image digest
+        id: id_get_service_digest
+        run: |
+          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $SERVICE_IMAGE_REPO:$SERVICE_IMAGE_TAG)
+          if [ -z "$DIGEST" ]; then
+            echo "Failed to retrieve digest for $SERVICE_IMAGE_REPO:$SERVICE_IMAGE_TAG"
+            exit 1
+          fi
+          echo "service_digest=$DIGEST" >> $GITHUB_OUTPUT
           
-      # - name: Update file with image digest
-      #   run: |
-      #     cd $GITHUB_WORKSPACE
-      #     SERVICE_FILE_PATH=service-image-digest.txt
-      #     BASE_FILE_PATH=base-image-digest.txt
-      #     SERVICE_IMAGE_DIGEST=${{ steps.id_get_service_digest.outputs.service_digest }}
-      #     BASE_IMAGE_DIGEST=${{ steps.id_get_base_digest.outputs.base_digest }}
+      - name: Update file with image digest
+        run: |
+          cd $GITHUB_WORKSPACE
+          SERVICE_FILE_PATH=service-image-digest.txt
+          BASE_FILE_PATH=base-image-digest.txt
+          SERVICE_IMAGE_DIGEST=${{ steps.id_get_service_digest.outputs.service_digest }}
+          BASE_IMAGE_DIGEST=${{ steps.id_get_base_digest.outputs.base_digest }}
           
-      #     # Handle service image digest file
-      #     if [ ! -f $SERVICE_FILE_PATH ]; then
-      #       touch $SERVICE_FILE_PATH
-      #     fi
-      #     echo "$SERVICE_IMAGE_DIGEST" >> $SERVICE_FILE_PATH
+          # Handle service image digest file
+          if [ ! -f $SERVICE_FILE_PATH ]; then
+            touch $SERVICE_FILE_PATH
+          fi
+          echo "$SERVICE_IMAGE_DIGEST" >> $SERVICE_FILE_PATH
 
-      #     # Handle base image digest file
-      #     if [ ! -f $BASE_FILE_PATH ]; then
-      #       touch $BASE_FILE_PATH
-      #     fi
-      #     echo "$BASE_IMAGE_DIGEST" >> $BASE_FILE_PATH
+          # Handle base image digest file
+          if [ ! -f $BASE_FILE_PATH ]; then
+            touch $BASE_FILE_PATH
+          fi
+          echo "$BASE_IMAGE_DIGEST" >> $BASE_FILE_PATH
 
-
-      # - name: Commit and push image digest
-      #   env:
-      #     GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-      #   run: |
-          # git config --global user.name 'GitHub Actions'
-          # git config --global user.email 'actions@github.com'
+      - name: Commit and push image digest
+        env:
+          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+        run: |
+          git config --global user.name 'GitHub Actions'
+          git config --global user.email 'actions@github.com'
           
-          # branch_name="update-image-digest"-${{ github.sha }}
-          # git checkout -b $branch_name
+          branch_name="update-image-digest"-${{ github.sha }}
+          git checkout -b $branch_name
 
-          # git add service-image-digest.txt
-          # git add base-image-digest.txt
-          # git commit -m "Update Docker image digest [ci skip]"
+          git add service-image-digest.txt
+          git add base-image-digest.txt
+          git commit -m "Update Docker image digest [ci skip]"
 
-          # # Set remote by authenticating with GITHUB_TOKEN
-          # git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
+          # Set remote by authenticating with GITHUB_TOKEN
+          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
 
-          # # Push changes to new branch
-          # git push origin HEAD:${branch_name}
+          # Push changes to new branch
+          git push origin HEAD:${branch_name}
 
-          # # Create a pull request using Github CLI
-          # gh pr create --title "Update new docker image digest" --body "This PR updates the new Docker image digest." --head ${branch_name} --base master
+          # Create a pull request using Github CLI
+          gh pr create --title "Update new docker image digest" --body "This PR updates the new Docker image digest." --head ${branch_name} --base master
 
-          # # Fetch the PR number and validate for auto-merge
-          # PR_NUMBER=$(gh pr list --state open --head ${branch_name} --json number --jq '.[0].number')
-          # if [ -z "$PR_NUMBER" ]; then
-          #   echo "No pull request found. Exiting..."
-          #   exit 1
-          # fi
-          # # Validate PR_NUMBER is a valid number
-          # if ! [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
-          #   echo "Invalid pull request number: $PR_NUMBER"
-          #   exit 1
-          # fi
+          # Fetch the PR number and validate for auto-merge
+          PR_NUMBER=$(gh pr list --state open --head ${branch_name} --json number --jq '.[0].number')
+          if [ -z "$PR_NUMBER" ]; then
+            echo "No pull request found. Exiting..."
+            exit 1
+          fi
+          # Validate PR_NUMBER is a valid number
+          if ! [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
+            echo "Invalid pull request number: $PR_NUMBER"
+            exit 1
+          fi
 
-          # # Auto-merge the pull request
-          # gh pr merge $PR_NUMBER --merge --delete-branch --body "[ci skip]"
+          # Auto-merge the pull request
+          gh pr merge $PR_NUMBER --merge --delete-branch --body "[ci skip]"
